@startuml
package "业务层" {
[异常国际化]
[VO国际化]
[数据集国际化]
}
note right of [数据集国际化]
 -
end note

package "核心层" {
[注解方式翻译]
[翻译api]
}
[VO国际化]-down->[注解方式翻译]
[注解方式翻译]-down->[翻译api]

package "数据层" {
  [翻译api实现]
  [数据源容器]
  [数据监控]
}
[翻译api] -down->[翻译api实现]
[翻译api实现]-down->[数据源容器]
package "数据层扩展" {
  [数据源1]
  [数据源2]
  [数据源3]
  [数据源4]
  [数据源5]
}

[数据源容器]-down->[数据源1]
[数据源容器]->[数据源2]
[数据源容器]->[数据源3]
[数据源容器]->[数据源4]
[数据源容器]->[数据源5]
@enduml
